package com.prabesh.growphasetech;

import com.prabesh.growphasetech.exceptions.InvalidNepaliDateException;
import com.prabesh.growphasetech.exceptions.UnsupportedBSYearException;

import java.time.LocalDate;

/**
 * An <strong>immutable</strong> Bikram Sambat (BS) date, represented as a
 * (year, month, day) triple.
 *
 * <p>This is a Java 21 {@code record}, meaning:</p>
 * <ul>
 *   <li>All fields are {@code final} and cannot be changed after construction.</li>
 *   <li>{@code equals()}, {@code hashCode()}, and a basic {@code toString()} are
 *       auto-generated by the compiler.</li>
 *   <li>Instances are safe to share across threads.</li>
 * </ul>
 *
 * <h2>Supported range</h2>
 * <p>BS 2000 (≈ AD 1943) through BS 2099 (≈ AD 2043). Outside this range,
 * an {@link UnsupportedBSYearException} is thrown.</p>
 *
 * <h2>Month numbering</h2>
 * <pre>
 *   1 = Baisakh   7  = Kartik
 *   2 = Jestha    8  = Mangsir
 *   3 = Ashadh    9  = Poush
 *   4 = Shrawan   10 = Magh
 *   5 = Bhadra    11 = Falgun
 *   6 = Ashwin    12 = Chaitra
 * </pre>
 *
 * <h2>Usage examples</h2>
 * <pre>{@code
 * // Today's date in Bikram Sambat
 * NepaliDate today = NepaliDate.today();
 *
 * // Construct explicitly
 * NepaliDate independenceDay = new NepaliDate(2063, 7, 2); // Kartik 2, 2063
 *
 * // Convert from Gregorian (AD)
 * NepaliDate fromAD = NepaliDate.fromAD(LocalDate.of(2025, 4, 14)); // Baisakh 1, 2082
 *
 * // Parse a slash/dash formatted string
 * NepaliDate parsed = NepaliDate.parse("2082/01/01");
 *
 * // Compare
 * boolean isFuture = parsed.isAfter(today);
 *
 * // Convert back to AD
 * LocalDate adDate = parsed.toAD();
 *
 * // Format for an official Nepali memo
 * String heading = NepaliDateFormatter.format(parsed, NepaliDateFormatter.Format.MEMO_HEADER_NP);
 * }</pre>
 *
 * @param year  Bikram Sambat year (2000–2099)
 * @param month BS month, 1 (Baisakh) through 12 (Chaitra)
 * @param day   day within the month; upper bound depends on the specific year+month
 *
 * @see NepaliDateConverter
 * @see NepaliDateFormatter
 * @see FiscalYear
 */
public record NepaliDate(int year, int month, int day)
        implements Comparable<NepaliDate> {

    // ── Compact constructor (runs before the implicit canonical constructor) ───

    /**
     * Compact constructor that validates all three fields before the record is
     * sealed as immutable.
     *
     * <p>Validation order:</p>
     * <ol>
     *   <li>Year must be in the supported range (2000–2099).</li>
     *   <li>Month must be 1–12.</li>
     *   <li>Day must be in 1..N, where N is the actual number of days in that
     *       specific year-month combination (looked up from {@link NepaliCalendarData}).</li>
     * </ol>
     *
     * @throws UnsupportedBSYearException  if {@code year} is outside 2000–2099
     * @throws InvalidNepaliDateException  if {@code month} or {@code day} is out of range
     */
    public NepaliDate {
        // 1. Year range check — NepaliCalendarData will also throw, but we give a
        //    clearer message here before we even touch the calendar data.
        if (!NepaliCalendarData.isYearSupported(year)) {
            throw new UnsupportedBSYearException(year);
        }

        // 2. Month range check (1–12)
        if (month < 1 || month > 12) {
            throw new InvalidNepaliDateException(
                "BS month must be between 1 and 12, got: " + month);
        }

        // 3. Day range check — maximum day varies by year AND month
        int maxDay = NepaliCalendarData.getDaysInMonth(year, month);
        if (day < 1 || day > maxDay) {
            throw new InvalidNepaliDateException(year, month, day, maxDay);
        }
    }

    // ── Static factory methods ────────────────────────────────────────────────

    /**
     * Returns the current date in Bikram Sambat, derived from the system clock
     * in the default time-zone.
     *
     * <p>Equivalent to {@code NepaliDate.fromAD(LocalDate.now())}.</p>
     *
     * @return today's date in BS
     */
    public static NepaliDate today() {
        return fromAD(LocalDate.now());
    }

    /**
     * Converts a Gregorian (AD) date to Bikram Sambat.
     *
     * @param adDate the Gregorian date; must not be {@code null} and must fall
     *               within the supported BS range (≈ AD 1943–2043)
     * @return the equivalent BS date
     * @throws NullPointerException        if {@code adDate} is {@code null}
     * @throws UnsupportedBSYearException  if the resulting BS year is outside 2000–2099
     */
    public static NepaliDate fromAD(LocalDate adDate) {
        if (adDate == null) throw new NullPointerException("adDate must not be null");
        return NepaliDateConverter.toBS(adDate);
    }

    /**
     * Parses a BS date from a string in the format {@code YYYY/MM/DD} or
     * {@code YYYY-MM-DD}.
     *
     * <p>Examples of accepted input: {@code "2082/04/15"}, {@code "2082-04-15"}.</p>
     *
     * @param dateStr the date string to parse; must not be {@code null}
     * @return the parsed {@code NepaliDate}
     * @throws InvalidNepaliDateException  if the string is not in a recognised format
     *                                     or the resulting date is invalid
     * @throws UnsupportedBSYearException  if the year is outside the supported range
     */
    public static NepaliDate parse(String dateStr) {
        if (dateStr == null) throw new NullPointerException("dateStr must not be null");

        // Split on either '/' or '-' — tolerates both separators
        String[] parts = dateStr.trim().split("[/\\-]");
        if (parts.length != 3) {
            throw new InvalidNepaliDateException(
                "Cannot parse BS date '" + dateStr + "'. "
                + "Expected format YYYY/MM/DD or YYYY-MM-DD.");
        }

        try {
            int y = Integer.parseInt(parts[0].trim());
            int m = Integer.parseInt(parts[1].trim());
            int d = Integer.parseInt(parts[2].trim());
            return new NepaliDate(y, m, d);
        } catch (NumberFormatException e) {
            throw new InvalidNepaliDateException(
                "Non-numeric component in BS date string: '" + dateStr + "'");
        }
    }

    // ── Conversion ────────────────────────────────────────────────────────────

    /**
     * Converts this BS date to its Gregorian (AD) equivalent.
     *
     * @return the corresponding {@link LocalDate} in the AD calendar
     */
    public LocalDate toAD() {
        return NepaliDateConverter.toAD(this);
    }

    // ── Calendar helpers ──────────────────────────────────────────────────────

    /**
     * Returns the Nepal fiscal year that this date falls in.
     *
     * <p>Nepal's fiscal year runs from <strong>Shrawan 1</strong> (month 4) of one
     * BS year to the last day of <strong>Ashadh</strong> (month 3) of the next.
     * Dates in Shrawan–Chaitra belong to the fiscal year starting in the same
     * calendar year; dates in Baisakh–Ashadh belong to the fiscal year that
     * started in the <em>previous</em> calendar year.</p>
     *
     * <pre>{@code
     * NepaliDate date = new NepaliDate(2082, 5, 10); // Bhadra 10, 2082
     * FiscalYear fy = date.getFiscalYear();
     * System.out.println(fy); // "2082/83"
     * }</pre>
     *
     * @return the {@link FiscalYear} containing this date
     */
    public FiscalYear getFiscalYear() {
        return FiscalYear.of(this);
    }

    /**
     * Returns the number of days in the month of this date.
     *
     * <p>Because BS day counts vary by year and month, this is a convenient
     * shorthand for {@code NepaliCalendarData.getDaysInMonth(year(), month())}.</p>
     *
     * @return total days in this date's month (typically 28–32)
     */
    public int lengthOfMonth() {
        return NepaliCalendarData.getDaysInMonth(year, month);
    }

    /**
     * Returns the total number of days in this date's BS year (365 or 366).
     *
     * @return days in the year
     */
    public int lengthOfYear() {
        return NepaliCalendarData.getDaysInYear(year);
    }

    // ── Comparison helpers ────────────────────────────────────────────────────

    /**
     * Returns {@code true} if this date is strictly before the given date.
     *
     * @param other the date to compare to; must not be {@code null}
     * @return {@code true} iff {@code this < other}
     */
    public boolean isBefore(NepaliDate other) {
        return compareTo(other) < 0;
    }

    /**
     * Returns {@code true} if this date is strictly after the given date.
     *
     * @param other the date to compare to; must not be {@code null}
     * @return {@code true} iff {@code this > other}
     */
    public boolean isAfter(NepaliDate other) {
        return compareTo(other) > 0;
    }

    /**
     * Returns {@code true} if this date is equal to the given date.
     *
     * <p>Note: the record's auto-generated {@code equals()} is already correct
     * for value comparison. This method is provided for fluent chaining and
     * readability alongside {@link #isBefore} / {@link #isAfter}.</p>
     *
     * @param other the date to compare to; must not be {@code null}
     * @return {@code true} iff year, month, and day are all equal
     */
    public boolean isEqual(NepaliDate other) {
        return compareTo(other) == 0;
    }

    /**
     * Returns {@code true} if this date lies within the closed interval
     * [{@code start}, {@code end}] (inclusive on both ends).
     *
     * @param start the start of the range (inclusive); must not be {@code null}
     * @param end   the end of the range (inclusive); must not be {@code null}
     * @return {@code true} iff {@code start <= this <= end}
     */
    public boolean isBetween(NepaliDate start, NepaliDate end) {
        return !isBefore(start) && !isAfter(end);
    }

    // ── Comparable ────────────────────────────────────────────────────────────

    /**
     * Compares this date with another BS date chronologically.
     *
     * <p>The comparison is performed by year first, then month, then day.
     * This ordering is consistent with {@code equals()} (since the record's
     * auto-generated {@code equals} is based on the same fields).</p>
     *
     * @param other the date to compare to; must not be {@code null}
     * @return negative if this is earlier, zero if equal, positive if later
     */
    @Override
    public int compareTo(NepaliDate other) {
        // Compare year first (most significant)
        if (this.year != other.year)   return Integer.compare(this.year,  other.year);
        // Then month
        if (this.month != other.month) return Integer.compare(this.month, other.month);
        // Finally day (least significant)
        return Integer.compare(this.day, other.day);
    }

    // ── Object overrides ──────────────────────────────────────────────────────

    /**
     * Returns this date as a string in {@code YYYY/MM/DD} format (e.g. {@code "2082/04/15"}).
     *
     * <p>This is the canonical short form used for data storage and logging.
     * For human-readable formatted dates (Nepali script, official headings, etc.),
     * use {@link NepaliDateFormatter}.</p>
     *
     * @return ISO-like BS date string with '/' separator
     */
    @Override
    public String toString() {
        // Zero-pad month and day to 2 digits for consistent output
        return "%d/%02d/%02d".formatted(year, month, day);
    }
}
